
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v5.10  Build: 5.10.0
-- SQL Server DDL Script generated from project: Stud1
-- Project filename: E:\Alex\Documents\LLBLGen Pro\v5.10\Projects\StudPass\Stud1.llblgenproj
-- Script generated on: 30-апр-2023 01:29.05
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Stud1'
-- ----------------------------------------------------------------------------------------------------------------

USE [Stud1]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Address] DROP CONSTRAINT [FK_cd004cc468aae6676f9b34c841e]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'dbo' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [dbo].[Address]
GO

DROP TABLE [dbo].[Person]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################

-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Stud1'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [Stud1] /* ON PRIMARY (NAME=Stud1_dat, FILENAME='c:\mycatalogs\Stud1.mdf', SIZE=10MB) */
GO


USE [Stud1]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[Address] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[State] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Region] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[City] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Street] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Apartment] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PersonId] [int] NULL 
)
GO

CREATE TABLE [dbo].[Person] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[LastName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[BirthDate] [datetime] NOT NULL, 
	[Gender] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Code] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Stud1'
-- ----------------------------------------------------------------------------------------------------------------

USE [Stud1]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Address] WITH NOCHECK 
	ADD CONSTRAINT [PK_f6b448741f29201aa4553ffa4de] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [dbo].[Person] WITH NOCHECK 
	ADD CONSTRAINT [PK_b73ee3942f1906d1acd81f06ec7] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Address] 
	ADD CONSTRAINT [FK_cd004cc468aae6676f9b34c841e] FOREIGN KEY
	(
		[PersonId] 
	)
	REFERENCES [dbo].[Person]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO



