//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Stud1.HelperClasses
{
	/// <summary>Field Creation Class for entity AddressEntity</summary>
	public partial class AddressFields
	{
		/// <summary>Creates a new AddressEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Id); }}
		/// <summary>Creates a new AddressEntity.State field instance</summary>
		public static EntityField2 State { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.State); }}
		/// <summary>Creates a new AddressEntity.Region field instance</summary>
		public static EntityField2 Region { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Region); }}
		/// <summary>Creates a new AddressEntity.City field instance</summary>
		public static EntityField2 City { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.City); }}
		/// <summary>Creates a new AddressEntity.Street field instance</summary>
		public static EntityField2 Street { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Street); }}
		/// <summary>Creates a new AddressEntity.Apartment field instance</summary>
		public static EntityField2 Apartment { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Apartment); }}
		/// <summary>Creates a new AddressEntity.PersonId field instance</summary>
		public static EntityField2 PersonId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.PersonId); }}
	}

	/// <summary>Field Creation Class for entity ParamEntity</summary>
	public partial class ParamFields
	{
		/// <summary>Creates a new ParamEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ParamFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity PersonEntity</summary>
	public partial class PersonFields
	{
		/// <summary>Creates a new PersonEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Id); }}
		/// <summary>Creates a new PersonEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Name); }}
		/// <summary>Creates a new PersonEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.LastName); }}
		/// <summary>Creates a new PersonEntity.BirthDate field instance</summary>
		public static EntityField2 BirthDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.BirthDate); }}
		/// <summary>Creates a new PersonEntity.Gender field instance</summary>
		public static EntityField2 Gender { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Gender); }}
		/// <summary>Creates a new PersonEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Code); }}
	}
	

}